name: Use Reusable Workflow

on:
  label:
    types:
      - created
  push:
    branches:
      - main
  page_build:
  pull_request:
    branches:
      - 'releases/**'
      - '!releases/**-alpha'

jobs:
  call-reusable-workflow:
    uses: enemchy/ci-test1/.github/workflows/blank.yml@main
    with:
      name: "GitHub"
