name: Use Reusable Workflow

run-name: Deploy

permissions: read-all

on: [ push ]
env:
  SERVER: production

# defaults:
#   run:
#     shell: bash
#     working-directory: ./scripts

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  some-job:
    uses: enemchy/ci-test1/.github/workflows/blank.yml@main
    with:
      name: "GitHub"
  # my_second_job:
  #   runs-on: ubuntu-latest
  #   name: My second job
